### ISSUE TITLE
Provide better messages on parse error

### ISSUE THREAD

**Issue by lihaoyi** [lihaoyi/Scalatex#14]
```
[error] /Users/haoyi/Dropbox (Personal)/Workspace/fastparse-root/readme/target/scala-2.11/src_managed/main/scalatex/Readme.scala:7: exception during macro expansion:
[error] java.lang.Exception: File:0 / Body:0 / BodyEx:0 / BodyItem:0 / SpecialIndented:1 / HeaderBlock:1 / Body:14 / BodyEx:14 / BodyItem:385 / SpecialIndented:387 / HeaderBlock:387 / Body:512 / BodyEx:512 / BodyItem:512 / SpecialIndented:514 / IndentScalaChain:514 / Body:610 / BodyEx:610 / BodyItem:22875 / SpecialIndented:22881 / IndentScalaChain:22881 / Body:22898 / BodyEx:22898 / BodyItem:24865 / SpecialIndented:24875 / IndentScalaChain:24875 / Body:24876 / BodyEx:24876 / BodyItem:24936 / Special:24937 / ScalaChain:24937 / Extension:24938 / ParenArgList:24938 / Exprs:24939 / Expr:25083 / (If | While | Try | DoWhile | For | Throw | Return | ImplicitLambda | SmallerExprOrLambda):25083 ...") using Fa"
[error] 	at scalatex.stages.Parser$.apply(Parser.scala:19)
[error] 	at scalatex.stages.Parser$.apply(Parser.scala:15)
[error] 	at scala.Function2$$anonfun$tupled$1.apply(Function2.scala:54)
[error] 	at scala.Function2$$anonfun$tupled$1.apply(Function2.scala:53)
[error] 	at scalatex.package$Internals$.compile$1(package.scala:83)
[error] 	at scalatex.package$Internals$.compileThing(package.scala:88)
[error] 	at scalatex.package$Internals$.applyMacroFileBase(package.scala:42)
[error] 	at scalatex.package$Internals$.applyMacroFile(package.scala:25)
[error]   def apply(): Frag = _root_.scalatex.twf("/Users/haoyi/Dropbox (Personal)/Workspace/fastparse-root/readme/Readme.scalatex")
[error]                                          ^
[error] one error found
[error] (readme/compile:compileIncremental) Compilation failed
[error] Total time: 3 s, completed May 10, 2015 8:39:03 PM
```

Since we already know exactly where the parse failed (we even show the index!) we should update the error location accordingly to show the source code rather than the synthesized macro call

**Comment by lihaoyi** [comment]
This has landed in trunk
