### ISSUE TITLE
Cannot generate html in a subdirectory

### ISSUE THREAD

**Issue by romainreuillon** [lihaoyi/Scalatex#4]
Hi,

an execption is throw if the destination of an html file is specified in a subdir:

```
  val site = new scalatex.site.Site {
    def content =
      Map(
        "index.html" -> Index(),
        "console/console.html" -> Console()
      )
  }
```

Raises this exception:

```
[info] Running Documentation /tmp/doc/
[error] (run-main-0) java.nio.file.NoSuchFileException: /tmp/doc/console/console.html
java.nio.file.NoSuchFileException: /tmp/doc/console/console.html
    at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
    at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
    at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
    at java.nio.file.Files.newOutputStream(Files.java:216)
    at java.nio.file.Files.write(Files.java:3292)
    at scalatex.site.Site$$anonfun$generateHtml$2.apply(Site.scala:130)
    at scalatex.site.Site$$anonfun$generateHtml$2.apply(Site.scala:125)
    at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:778)
    at scala.collection.immutable.Map$Map3.foreach(Map.scala:161)
    at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:777)
    at scalatex.site.Site$class.generateHtml(Site.scala:125)
    at Documentation$$anon$1.generateHtml(Documentation.scala:22)
    at scalatex.site.Site$class.renderTo(Site.scala:140)
    at Documentation$$anon$1.renderTo(Documentation.scala:22)
    at Documentation$.delayedEndpoint$Documentation$1(Documentation.scala:30)
    at Documentation$delayedInit$body.apply(Documentation.scala:20)
    at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
    at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
    at scala.App$$anonfun$main$1.apply(App.scala:76)
    at scala.App$$anonfun$main$1.apply(App.scala:76)
    at scala.collection.immutable.List.foreach(List.scala:381)
    at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
    at scala.App$class.main(App.scala:76)
    at Documentation$.main(Documentation.scala:20)
    at Documentation.main(Documentation.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
```

Romain

**Comment by romainreuillon** [comment]
Regression?
